replicaCount: 2

image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: "6.7.0"
  pullPolicy: IfNotPresent

containerPort: 9898

service:
  type: ClusterIP
  port: 80

probes:
  path: /healthz

resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits: { cpu: 250m, memory: 256Mi }

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

env: {}
