apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
  labels: {{- include "web-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "web-app.selector" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
